config/routes.rb
Rails.application.routes.draw do
  root :to => "events#index"
  devise_for :users
  resources :users
  resources :events
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :administrator, class_name: "User"
  has_many :attendances
  has_many :users, through: :attendances
  
  validates :title, length: { in: 5..140, message: "must be between 5 and 140 charachters" }
  validates :start_date, presence:true
  validates :duration, presence:true, numericality: { only_integer: true, greater_than: 0 }
  validates :price, presence:true, numericality: { only_integer: true, greater_than: 0, less_than: 1000 }
  validates :location, presence:true
  validates :description, presence:true, length: { in: 20..1000, message: "must be between 20 and 1000 charachters" }
  validates :modulo5?, presence:true
  validates :already_past?, presence:true
  validates :modulo5?, presence:true
  


  private

  def modulo5?
    duration % 5 == 0 ? true : errors.add(:duration, "must be a five multiple")
  end

  def already_past?
    if start_date < Time.now
      errors.add(:start_date, " already past")
    else
      true
    end 
  
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send
 

  has_many :attendances
  has_many :events, through: :attendances
  has_many :event_admin, foreign_key: 'administrator_id', class_name: "Event"

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def is_current_user?
    current_user.id==params[:id]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  def index
    @events=Event.all
    
  end

  def show
    @event=Event.find(params[:id])
  end

  def new
    @newevent=Event.new
  end

  def create    
    event_params = params[:event]
    @newevent = Event.new(title: event_params[:title], description: event_params[:description], start_date: event_params[:start_date].to_datetime, duration: event_params[:duration], price: event_params[:price], location: event_params[:location], administrator: current_user)

    if @newevent.save 
      
      flash[:notice] = "Event successfully created"
      redirect_to root_path
    else
      render new_event_path
    end

  end

  def destroy
    @event=Event.find(params['id'])
    @event.destroy
    flash[:notice] = "Event successfully deleted"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :only_see_own_page, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def is_current_user?
    
    unless current_user.id!=params[:id]
      flash[:notice] = "Please log in."
      redirect_to new_user_session_path
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_update)
      flash[:success] = "User succesfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def only_see_own_page
    @user = User.find(params[:id])
  
    if current_user != @user
      redirect_to root_path, notice: "Sorry, but you are only allowed to view your own profile page."
    end
  end
  def user_update
    params.require(:user).permit(:first_name, :last_name, :description, user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold">EventBriteLike - So what?</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <h3 class="text-white-75 font-weight-light mb-5">Bienvenue!</h3>
          <a class="btn btn-primary btn-xl js-scroll-trigger btn-update" href="#about">Find Out More (Ou pas!)</a>
        </div>
      </div>
    </div>
  </header>

  <!-- Services Section -->
  <section class="page-section" id="services">
    <div class="container">
      <h2 class="text-center mt-0"><a href="<%=new_event_path%>">Créer un event</a></h2><br>
      <hr class="divider my-4"><br>
      <h2 class='text-center mt-0'> Event du jour </h2><br>
      <hr class="divider my-4"><br>
      <div class="container d-flex flex-wrap justify-content-around">
        <% @events.each_with_index do |event,index| %>
            <div class="card mt-5" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title"><%= event.title.capitalize %><br/></h5>
                <h6 class="card-subtitle mb-2 text-muted">Organisateur : <%= event.administrator.first_name %><br/></h6><br/>
                <h6 class="card-subtitle mb-2 text-muted">Démarrage : <%= event.start_date %><br/></h6><br/>
                <p class="card-text"> Description : <%= event.description%></p><br/>
                <p class="card-text"> Prix : <%= event.price%>€</p><br/>
                <p class="card-text"> Localisation : <%= event.location%></p><br/>

                
                <%if current_user%>

                <%else%>

                <%end%>
                </h6>
                <hr class="divider my-4">

                
                <a class="btn btn-primary btn-update" href="<%=event_path(event.id)%>" role="button">Voir</a>
                <% if event.administrator == current_user %>
                <a class="btn btn-success" href="#" role="button">Editer "à venir"</a>
                <a class="btn btn-warning" href="<%=event_path(event.id)%>" role="button" data-confirm="Etes-vous sur?" data-method="DELETE" >Supprimer</a>
                <%end%>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </section>

app/views/events/new.html.erb
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <div class="container">
            <div class="card text-center">
              <div class="card-header">
                 
              </div>
              <div class="card-body">
                <h4 class="card-title">Crée ton Evénement</h4><br/>
                <p class="card-text">  
                          <% if @newevent.errors.any? %>
                            <div class="alert alert-danger" role="alert">
                              <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
                              <ul>
                                <% @newevent.errors.full_messages.each do |message| %>
                                  <li><%= message %></li>
                                <% end %>
                              </ul>
                            </div>
                          <% end %>
                
                <%= form_for @newevent, url: events_path, html: {method: :post, class: "form-signin mt-3" } do |f| %>

                  <div class="field">
                    <%= f.label :title %><br />
                    <%= f.text_field :title, autofocus: true, autocomplete: "title" %>
                  </div>

                  <div class="field">
                    <%= f.label :description %><br />
                    <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
                  </div>

                  <div class="field">
                    <%= f.label :location %><br />
                    <%= f.text_field :location, autofocus: true, autocomplete: "location" %>
                  </div>

                  <div class="field">
                    <%= f.label :duration %><br />
                    <%= f.number_field :duration, autofocus: true,in: 5..180, step: 5, autocomplete: "duration" %>
                  </div>

                  <div class="field">
                    <%= f.label :price %><br />
                    <%= f.number_field :price, autofocus: true,in: 1..1000, step:1, autocomplete: "price" %>
                  </div>

                  <div class="field">
                    <%= f.label :start_date %><br />
                    <%= f.date_field :start_date, autofocus: true, autocomplete: "start_date" %>
                  </div><br/>


                <button type='submit' class="btn btn-update"> Créer l'évenement </button>
                

                <%end%>
                
                </p>
                <div class="text-muted">
                  
                </div><br/>
                
              </div>
              <div class="card-footer text-muted">


              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5"></p>
          
        </div>
      </div>
    </div>
  </header>

app/views/events/show.html.erb
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <div class="container">
            <div class="card text-center">
              <div class="card-header">
                 Organnisateur : <%=@event.administrator.first_name%>
              </div>
              <div class="card-body">
                <h4 class="card-title"><%=@event.title.capitalize %></h4>
                <p class="card-text">Description : <%= @event.description %></p>
                <p class="card-text">Prix : <%= @event.price %>€</p>
                <p class="card-text"> Durée : <%= @event.duration %> minutes</p>
                <p class="card-text">Lieu : <%= @event.location %></p>
                <p class="card-text">Date : <%= @event.start_date %></p>
                <div class="text-muted">
                 
                </div><br/>
                <%if @event.administrator==current_user %>
                <a class="btn btn-success" href="#" role="button">Editer "à venir"</a>
                <a class="btn btn-warning" href="<%=event_path(@event.id)%>" role="button" data-confirm="Etes-vous sur?" data-method="DELETE" >Supprimer</a>
                <%end%>
              </div>
              <div class="card-footer text-muted">
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5"></p>
          
        </div>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Event Brite Like</title>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Theme CSS - Includes Bootstrap -->

  <%= stylesheet_link_tag "creative.min.css" %>
  <%= stylesheet_link_tag "styles.css" %>
  <%= stylesheet_link_tag "all.min.css" %>
  <%= stylesheet_link_tag "magnific-popup.css" %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">
  
</head>

<body id="page-top">


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      
      <a class="navbar-brand js-scroll-trigger" href="<%=root_path%>">EventBriteLike</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in?%>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="<%=user_path(current_user.id)%>">Mon profil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="<%=destroy_user_session_path%>"data-confirm="Etes-vous sur?" data-method="DELETE">Se Déconnecter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="<%=new_event_path%>">Créer un event</a>
          </li>
        </ul>
      </div>
    </div>
      <%else%>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="<%=new_user_registration_path%>">S'inscrire</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="<%=new_user_session_path%>">Se Connecter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="">Créer un event</a>
          </li>
        </ul>
      </div>
    </div>
    <%end%>
    <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert"><%= flash[:notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    <% end %>
  </nav>


<%= yield %>


  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="small text-center text-muted">Copyright &copy; 2019 - GossipBook</div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="/assets/vendor/jquery/jquery.min.js"></script>
  <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
 

  <!-- Plugin JavaScript -->
  <script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>
  <script src="/assets/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="/assets/js/creative.min.js"></script>
  <%= javascript_include_tag :application%>
  <%= csrf_meta_tags %>


</body>

</html>

app/views/users/edit.html.erb
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <div class="card text-center">
            <div class="card-header">
              <h2>Editer le profil</h2>
            </div>
            <div class="card-body">
            <%= form_for @user do |f| %>


              <p class="card-text">
              <div class="field">
                      <%= f.label :first_name %><br />
                      <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
                      </div>
              </p>

              <p class="card-text">
              <div class="field">
                      <%= f.label :last_name %><br />
                      <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
                      </div>
              </p>

              <p class="card-text">
              <div class="field">
                      <%= f.label :description %><br />
                      <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
                      </div>
              </p>

              <p class="card-text">
              <div class="actions">
                        <button type="submit" class="btn btn-outline-primary">Update</button>
                        
                      </div>
              </p>
              
              <% end %>
              
            </div>
            <div class="card-footer text-muted">
              
            </div>
          </div>

        
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">

        </div>
      </div>
    </div>
  </header>

app/views/users/show.html.erb
  <!-- Masthead -->
  <header class="masthead">
        <div class="row h-100 align-items-center justify-content-center text-center">
          <div class="col-lg-10 align-self-end">        
              <div class="container align-items-center justify-content-center text-center d-flex">
                <div class="container">
                  <U><h2>Profil de <%= @user.first_name  %></h2></U><br/>
                  <%= image_tag("profil.jpg", class: "figure-img rounded user") %>
                  <a href="<%=edit_user_path%>" class="btn btn-info">Editer le profil</a>
                  <a href="<%=edit_user_registration_path%>" class="btn btn-info">Editer email/password</a>
                </div>
                
                <div class="container align-left">
                  Nom complet : <%= @user.first_name  %> <%= @user.last_name  %><br><br>
                  Email : <%= @user.email  %><br><br>
                  Description : <%= @user.description  %><br> <br>
                </div>
                
              </div>    
              
          </div>
          <div class="col-lg-8 align-self-baseline">          
          </div>
        </div>
  </header>